### ISSUE TITLE
Is there any ablation about the two losses?

### ISSUE THREAD

**Issue by ha-lins** [RingBDStack/SUGAR#1]
Hi @Suchun-sv @SunQingYun1996,

Thanks for the great work! I wonder if there are any ablation studies such as: `SUGAR w/o supervised loss` or `SUGAR w/o self-supervised contrastive loss` or `SUGAR w/o reinforcement pooling`. I think it will validate the effects of each module better. 
I'm studying unsupervised graph representation learning and the effect of `SUGAR w/o supervised loss` could inspire me in some way.

Thanks!

**Comment by SunQingYun1996** [comment]
Thank you for your interest. For the ablation study of self-supervised contrastive loss, we show the results with different self-supervised loss coefficients in Figure 4 (f), where the coefficient beta 0 represents the performance of SUGAR without self-supervised contrastive loss. For the ablation study of reinforcement pooling, we show the results in Figure 4 (a), where SUGAR-FixedK represents SUGAR without reinforcement pooling.

**Comment by ha-lins** [comment]
Thanks for your reply. Now I understand SUGAR is mainly a supervised learning approach. Btw, I think it would be interesting to see how SUGAR performs in the completely unsupervised scenario (e.g., with just the MI loss). Do you have any intuitions about such performance? @SunQingYun1996 Thanks!

**Comment by SunQingYun1996** [comment]
Sorry for the late reply. The main intuition of SUGAR is representing the graph as striking and label-relevant subgraphs. I don't think the subgraph selection mechanism can perform well in the completely unsupervised scenario.

**Comment by ha-lins** [comment]
Thanks for the reply!
